version: "3.7"

services:

  python:
    build:
      context: "./Docker/python"
    ports:
      -80:80
    volumes:
      -./src/python:/etc

  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - "./Docker/volumes/mysql:/var/lib/mysql"
