version: "3.7"

services:

  python:
    build:
      context: "./Docker/python"
    ports:
      - "8080:80"
    volumes:
      - "./Docker/volumes/python:/usr/src/app"

  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - "./Docker/volumes/mysql:/var/lib/mysql"
